### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by aman-rapidops** [rehanRapid/Company#1]
1. Please give the proper filename & spelling must be correct and it must be in camel case. See below
     
![Screenshot from 2023-06-12 15-02-06](https://github.com/rehanRapid/Company/assets/97516821/fbdba866-b565-4bdd-9f1c-54b6e90daf4e)

2. Exception name must be in pascal case. Do the same changes in all required files.

![Screenshot from 2023-06-12 15-14-42](https://github.com/rehanRapid/Company/assets/97516821/9c733062-c2f1-4f32-85fa-d330c7de6bef)

3. Change "makeCreateEmployeUsecase" or "createEmployeUsecase" to "makeCreateEmployee" or "createEmployee". And "validInput" to "validateInput" or "validateInputData". Do the same changes in all required files.
![Screenshot from 2023-06-12 15-20-50](https://github.com/rehanRapid/Company/assets/97516821/6f9e12bb-6cee-4a4b-a69f-73100d7bd428)

4. Remove Line no 7. 
  
![Screenshot from 2023-06-12 16-05-24](https://github.com/rehanRapid/Company/assets/97516821/6ccbd441-638e-43aa-b730-d4b87f9a9443)

5. Whenever you're deleting something by id, pass it in params rather than the body. And also here, the forbidden error not comes & please throw it from the use-case.
![Screenshot from 2023-06-12 16-09-39](https://github.com/rehanRapid/Company/assets/97516821/bc028bf3-873a-42aa-936c-9bf86491e9e1)

6. Please add test cases for all use cases.
7. Don't need to make two use cases for "getCompanyByName". Both are doing the same work. So, remove it.
![Screenshot from 2023-06-12 16-26-50](https://github.com/rehanRapid/Company/assets/97516821/a97ff52c-b3e1-43bb-a19f-0e52c7bec50b)

8. You can directly check if(!companies.length) & throw error.
   
![Screenshot from 2023-06-12 16-35-47](https://github.com/rehanRapid/Company/assets/97516821/5f505be6-1653-4b05-8a45-2b23af5682c3)

9. Don't create a new variable & then return. Simply add the "return" keyword before the function call
  
![Screenshot from 2023-06-12 16-42-47](https://github.com/rehanRapid/Company/assets/97516821/76c18d24-da25-4c32-b2a7-8b2b848dcca8)

 Fix these issues & common mistakes that I posted in a group for all the required files.

**Comment by rehanRapid** [comment]
done the changes
